version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - touch file01.zip
      - touch file02.zip
      - touch file03.zip
      - ls -la /codebuild
  post_build:
    commands:
      - rm -rf /tmp/output-dir && mkdir /tmp/output-dir
      - find . -name "*.zip" -exec cp {} /tmp/output-dir \;
      - ls -la /tmp/output-dir
artifacts:
  base-directory: /tmp/output-dir
  files:
    - '*'
